log:
  level: warn
  file: "/tmp/mosdns.log"

api:
  http: "127.0.0.1:9091"

include: []

plugins:
  - tag: ad_domains
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/adblockmosdns.txt"

  - tag: ad_allowlist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/adblock-allowlist.txt"

  - tag: forward_openclash
    type: forward
    args:
      upstreams:
        - addr: "127.0.0.1:7874"

  - tag: main_sequence
    type: sequence
    args:
      - matches:
          - qname $ad_domains
          - "!qname $ad_allowlist"
        exec: reject 3
      - exec: $forward_openclash

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: "127.0.0.1:5335"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: "127.0.0.1:5335"
